version: '3.3'

services:

  application:
    build: .

    depends_on:
      database:
       condition: service_started
    
    env_file:
      - ./configuration.env


    ports:
      - "3000:3000"
    
    volumes:
      - .:/app
    

  database:
    image: postgres:16.3

    env_file:
      - ./configuration.env
      
        
    volumes:
      - db-data:/var/lib/postgresql/data
    
    ports:
      - 54340:5432


volumes:
  db-data:
