version: '3.3'

services:

  application:
    build: .

    depends_on:
      database:
       condition: service_started
    
    environment:
     - DB_CONN_STRING=${DB_CONN_STRING}


    ports:
      - "3000:3000"
    
    volumes:
      - .:/app
    

  database:
    image: postgres:16.3
    
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
    volumes:
      - db-data:/var/lib/postgresql/data
    
    ports:
      - 54340:5432


volumes:
  db-data:
