version: '3.3'

services:

  app:
    build: .
    depends_on:
      db:
        condition: service_started
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ruchita
      POSTGRES_PASS: qwerty
      POSTGRES_DB: orville_project
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    # command: ["stack", "exec", "OrvilleProject-exe"]



  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: ruchita
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: orville_project
      # PATH: "/app/.stack-work/install/x86_64-linux/9426f635756deea4d1c1a15610c4d68acba70ff55dc117e9cf2bba60ad1d0bee/9.6.6/bin"

    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"



volumes:
  db-data:
