name:               OrvilleProject
version:            0.1.0.0
visibility:         public
id:                 OrvilleProject-0.1.0.0-inplace
key:                OrvilleProject-0.1.0.0-inplace
license:            MIT
maintainer:         rmganurkar1323@gmail.com
author:             RuchitaGanurkar
category:           Database
abi:                inplace
exposed:            True
data-dir:           /home/adming10x/G10X/SPUR/OrvilleProject/.
depends:
    aeson-2.2.3.0-fe9f9597efcfac6bbde63bf45f38c019dfa3231c8f190526eeea7c92eca8c6ef
    base-4.14.3.0 mtl-2.2.2 orville-postgresql-1.1.0.0-inplace
    postgresql-libpq-0.10.1.0-3560cfd7de9f540b1ac7b1fda22dec3c5478f1db4f5fc9aa589d1760be9b6f10
    servant-0.20.1-e37f7abf9ca870312782e8948d5b1553d9b558ce870110c2eba1f70ec2c153d8
    servant-server-0.20-13217d2cbc3e45f4ca31b9ccff4479b808dad5fd39a526536760fb62b2a7801f
    text-1.2.4.1
    vector-0.13.1.0-ef53256ddd7dac3be68151b4dcc07ecc8a8354b7efc6c17f2d2740ebb91bc3b1
    wai-3.2.4-e83359e3ba98a2f50613b98e1e4fbaeb52ca595d3b33b735fa7325b93d8f670b
    warp-3.4.1-bc300cb74e74051f1a16e3d15198c70682cfc5a6a40aba01bd0b6016eaa506ea

haddock-interfaces:
    /home/adming10x/G10X/SPUR/OrvilleProject/dist-newstyle/build/x86_64-linux/ghc-8.10.7/OrvilleProject-0.1.0.0/doc/html/OrvilleProject/OrvilleProject.haddock

haddock-html:
    /home/adming10x/G10X/SPUR/OrvilleProject/dist-newstyle/build/x86_64-linux/ghc-8.10.7/OrvilleProject-0.1.0.0/doc/html/OrvilleProject
